import Head from 'next/head'
import EdgeShape from '../public/img/edge.svg'
//import Image from 'next/image'
//import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500">
        <div className="main container max-w-screen-xl mx-auto px-5 py-5 bg-slate-200">
          <div className='main-container-inner'>
            <div>
              <EdgeShape />
            </div>
            <div className='inner-container'>
              <header>

              </header>
              <main>

              </main>
              <footer>

              </footer>
              <div className='absolute bottom-0 right-0'>
                <EdgeShape />
              </div>
            </div>
          </div>

        </div>
      </div>
      
    </>
  )
}