import Head from 'next/head'
import EdgeShape from '../public/img/edge.svg'
//import Image from 'next/image'
//import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500">
        <div className="main container max-w-screen-xl m-auto object-center  bg-slate-200">
            <div className="flex flex-row">
              <div className="basis-1/3"><div>
                <EdgeShape />

              </div></div>
              <div className="basis-1/3"><div className="absolute inset-0 flex justify-center items-center ">
                <p className="text-5xl font-bold px-35">Hello</p>
              </div></div>
              <div className="basis-1/3"> 
              <p>yalla</p>            
              <div className='rotate-180'>
                <EdgeShape />
              </div></div>
            </div>

            <div className="absolute inset-0 flex justify-center items-center ">
              <p className="text-5xl font-bold px-35">Hello</p>
            </div>              <main>

            </main>
            <footer>

            </footer>


        </div>
      </div>

    </>
  )
}